server:
  ws:
    port: 8887
    address: 0.0.0.0
  port: 8888
spring:
  application:
    name: tt-cloud-infra
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
    dbcp2:
      test-while-idle: true
      validationQuery: SELECT 1
      timeBetweenEvictionRunsMillis: 60000
    tomcat:
      max-wait: 15000
      max-active: 50
      test-on-borrow: true
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: update