spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/iEnergy
    username: postgres
    password: admin
    hikari:
      poolName: Hikari
      auto-commit: false
